core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data_generator.urls')),


    path('celery-progress/', include('celery_progress.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

data_generator/urls.py
from django.urls import path, include

from . import views

app_name = 'data_generator'

urlpatterns = [
    path('', views.list_all_schemas, name='schemas'),

    path('', include('django.contrib.auth.urls')),

    path('create_schema/', views.create_schema, name='create_schema'),
    path('delete_schema/<int:id>/', views.delete_schema, name='delete_schema'),
    path('edit_schema/<int:id>/', views.edit_schema, name='edit_schema'),
    path('view_schema/<int:id>/', views.schema_view, name='schema_view'),

    path('view_schema/<int:schema_id>/delete_file/<int:file_id>/',
         views.delete_csv_file, name='delete_csv'),

]

data_generator/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


class SchemaStatusChoises:
    READY = "Ready"
    PROCESSING = "Processing"
    FAILED = "Failed"

    CHOICES = (
        (READY, "Ready to download"),
        (PROCESSING, "In progress"),
        (FAILED, "Error"),
    )


class ColumnTypeChoices:
    INT = "integer"
    DATE = "date"
    EMAIL = "email"
    PHONE = "phone"
    JOB = "job"
    NAME = "name"

    CHOICES = (
        (NAME, "Full name"),
        (INT, "Number range"),
        (DATE, "Date time"),
        (EMAIL, "E-mail"),
        (PHONE, "Phone number"),
        (JOB, "Job"),
    )


class Schema(models.Model):
    """Parameters for schema for csv files"""
    name = models.CharField(max_length=255, verbose_name='Name')
    separator = models.CharField(max_length=1,
                                 default=',',
                                 verbose_name='Separator')
    status = models.CharField(choices=SchemaStatusChoises.CHOICES,
                              max_length=255,
                              verbose_name='Status')
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             blank=True,
                             null=True,
                             verbose_name='User')
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='Created at')

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return 'The schema {} created at {}'.format(self.name, self.created_at)


class SchemaFile(models.Model):
    """Parameters for csv files"""
    file = models.FileField(blank=True, null=True,
                            verbose_name="Files with data")
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE,
                               related_name='schema_files')
    status = models.CharField(choices=SchemaStatusChoises.CHOICES,
                              max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ('-created_at',)


class SchemaColumnModel(models.Model):
    """Parameters and columns for generating csv file"""
    name = models.CharField(max_length=255, verbose_name='Name')
    column_type = models.CharField(choices=ColumnTypeChoices.CHOICES,
                                   max_length=30)
    integer_range_from = models.PositiveSmallIntegerField(null=True,
                                                          blank=True,
                                                          verbose_name='From')
    integer_range_to = models.PositiveSmallIntegerField(null=True,
                                                        blank=True,
                                                        verbose_name='To')
    order = models.PositiveSmallIntegerField(default=1,
                                             validators=[MinValueValidator(1)],
                                             verbose_name='Column order')
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE, null=True,
                               blank=True, verbose_name='Schema',
                               related_name='column_in_schemas')

    class Meta:
        verbose_name = "Column in schema"
        verbose_name_plural = "Columns in schema"

    def __str__(self):
        return "Column {} in schema".format(self.name)

data_generator/forms.py
from django import forms

from .models import Schema, SchemaColumnModel


class SchemaForm(forms.ModelForm):
    class Meta:
        model = Schema
        fields = ('name', 'separator',)


ColumnFormset = forms.modelformset_factory(
    SchemaColumnModel,
    fields=('name', 'column_type', 'integer_range_from',
            'integer_range_to', 'order'),
    extra=4,
)


class RowsForm(forms.Form):
    rows = forms.IntegerField()

data_generator/views.py
import os
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.decorators import login_required

from .models import Schema, SchemaColumnModel
from .forms import SchemaForm, ColumnFormset, RowsForm
from .tasks import create_csv_file


@login_required
def list_all_schemas(request):
    """Display all schemas belong to current user"""
    user = User.objects.get(id=request.user.id)
    all_schemas = Schema.objects.filter(user=user)

    context = {"schemas": all_schemas}
    return render(request, 'data_generator/list_all_schemas.html', context)


@login_required
def create_schema(request):
    """Create schema instance with chosen columns"""
    user = User.objects.get(id=request.user.id)
    schema_form = SchemaForm(request.GET or None)
    formset = ColumnFormset(queryset=SchemaColumnModel.objects.none())

    if request.method == 'POST':
        schema_form = SchemaForm(request.POST)
        formset = ColumnFormset(request.POST)
        if schema_form.is_valid() and formset.is_valid():
            schema = schema_form.save(commit=False)
            schema.user = user
            schema = schema_form.save()

            for form in formset:
                column = form.save(commit=False)
                column.schema = schema
                column.save()
            return redirect('data_generator:schemas')
        else:
            return HttpResponse(
                'Some of your fields filled incorrect. Try again.')

    context = {'schema_form': schema_form, 'formset': formset}
    return render(request, 'data_generator/create_schema.html', context)


@login_required
def edit_schema(request, id):
    """Edit schema instance"""
    schema = Schema.objects.get(id=id)
    schema_form = SchemaForm(instance=schema)
    Formset = forms.modelformset_factory(SchemaColumnModel,
                                         extra=0,
                                         fields=[
                                             'id',
                                             'name',
                                             'column_type',
                                             'integer_range_from',
                                             'integer_range_to',
                                             'order'
                                         ])
    formset = Formset(
        initial=[{"id": x.id} for x in schema.column_in_schemas.all()],
        queryset=SchemaColumnModel.objects.filter(schema_id=id))

    if request.method == 'POST':
        schema_form = SchemaForm(request.POST, instance=schema)
        formset = ColumnFormset(request.POST, initial=[
                                x for x in schema.column_in_schemas.all()])
        if schema_form.is_valid() and formset.is_valid():
            schema = schema_form.save()
            formset.save()
            return redirect('data_generator:schemas')
        else:
            return HttpResponse(
                'Some of your fields filled incorrect. Try again.')

    context = {'schema_form': schema_form, 'formset': formset}
    return render(request, 'data_generator/edit_schema.html', context)


@login_required
def delete_schema(request, id):
    """Delete schema instance with all columns"""
    schema = Schema.objects.get(id=id)
    schema.delete()
    return redirect('data_generator:schemas')


@login_required
def schema_view(request, id):
    """Display a list of created csv files and their status"""
    schema = Schema.objects.get(id=id)
    form = RowsForm(request.POST or None)

    if request.method == 'POST':
        rows = int(request.POST.get('rows'))

        generating_task = create_csv_file.delay(schema.id, rows)

        task_id = generating_task.task_id

        context = {'schema': schema, 'form': form, 'task_id': task_id}
        return render(request, 'data_generator/schema_view.html', context)
    else:
        form = RowsForm()
    context = {'schema': schema, 'form': form}
    return render(request, 'data_generator/schema_view.html', context)


@login_required
def delete_csv_file(request, schema_id, file_id):
    """Delete created csv file from db and local storage"""
    schema = Schema.objects.get(id=schema_id)
    file = schema.schema_files.get(id=file_id)
    try:
        path_to_csv_file = settings.MEDIA_ROOT + str(file.file)
        os.remove(path_to_csv_file)
    except:
        pass

    file.delete()
    return redirect('data_generator:schema_view', schema.id)

data_generator/templates/data_generator/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>CSVGenerator</title>

	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	
</head>
<body>

	<div class="container">
	    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
	      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
	        <h4>CSV Generator</h4>
	      </a>

	      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
	        <li><a href="/" class="nav-link px-2 link-secondary">Schemas</a></li>
	      </ul>

	      {% if request.user.is_authenticated %}
	      	<div class="col-md-3 text-end">
		      	<span style="font-size: 18px; margin-right: 10px;">welcome, {{ request.user }}</span>
		        <a href="{% url 'data_generator:logout' %}" type="button" class="btn btn-outline-primary me-2">Logout</a>
		      </div>
	      {% else %}
		      
	      {% endif %}
	    </header>
	 </div>

	{% block content %}{% endblock content %}

	<!-- Celery Progress -->
	<script src="{% static 'celery_progress/celery_progress.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
	<!-- JQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Bootstrap JS -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

	{% block custom_scripts %}{% endblock custom_scripts %}


</body>
</html>

data_generator/templates/data_generator/create_schema.html
{% extends 'data_generator/base.html' %}


{% block content %}

	<div class="container">
        <div class="row mt-4">
            <form method="POST" action="" class="form-inline">
                {% csrf_token %}
                {{ schema_form.as_p }}

                <hr>
                <div id="form-container">
	                {{ formset.management_form }}
	                {% for forms in formset %}
	                <div class="row schema-form mt-3">
	                	{% for field in forms.visible_fields %}
	                    <div class="form-group col">
	                        <label class="form-label">{{ field.label }}</label>
	                        {{ field }}
	                    </div>
	                   	{% endfor %}
	                   	<button class=" mt-4 btn btn-danger btn-sm col-md remove-form" type="button">Delete</button>
	                	
	                </div>
	                {% endfor %}
	                <button id="add-form" class="btn btn-primary mt-2" type="button">Add Another column</button>
	                <button class="btn btn-success float-right mt-2" type="submit">Create</button>
	            </div>
    		</form>
    	</div>
    </div>	
{% endblock %}


{% block custom_scripts %}
    {% include 'js/add_extra_form_field.html' %}
{% endblock custom_scripts %}

data_generator/templates/data_generator/edit_schema.html
{% extends 'data_generator/base.html' %}


{% block content %}

	<div class="container">
        <div class="row mt-4">
            <form method="POST" action="" class="form-inline">
                {% csrf_token %}
                {{ schema_form.as_p }}

                <hr>
                <div id="form-container">
                    {{ formset.management_form }}
                    {% for forms in formset %}
                        {% for form in formset %}
                            {% for hidden in form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            <!-- form.visible fields go here -->
                        {% endfor %}
                    <div class="row schema-form mt-3">
                    	{% for field in forms.visible_fields %}
                        <div class="form-group col">
                            <label class="form-label">{{ field.label }}</label>
                            {{ field }}

                            {% for error in field.errors %}
                                <span class="help-block">{{ error }}</span>
                            {% endfor %}
                        </div>
                       	{% endfor %}
                       	<button class=" mt-4 btn btn-danger btn-sm col-md remove-form" type="button">Delete</button>
                    	
                    </div>
                    {% endfor %}
                    <button id="add-form" class="btn btn-primary mt-2" type="button">Add Another column</button>
                    <button class="btn btn-success float-right mt-2" type="submit">Update</button>
                </div>
    		</form>
    	</div>
    </div>	
{% endblock %}


{% block custom_scripts %}
    {% include 'js/add_extra_form_field.html' %}
{% endblock custom_scripts %}

data_generator/templates/data_generator/list_all_schemas.html
{% extends "data_generator/base.html" %}

{% block content %}

<div class="container">
        <div class="row mt-4">

            <h3>Data schemas</h3>
            <a class="btn btn-success col-md-2" href="{% url 'data_generator:create_schema' %}">Create schema</a>

            <table class="table mt-3">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Modified</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for schema in schemas %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'data_generator:schema_view' schema.id %}">{{ schema.name }}</a></td>
                        <td>{{ schema.created_at }}</td>
                        <td>
                            <span>
                                    <a class="text-warning" href="{% url 'data_generator:edit_schema' schema.id %}">Edit</a>
                            </span>

                            <span>
                                <a class="text-danger" href="{% url 'data_generator:delete_schema' schema.id %}">Delete</a>
                            </span>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>

            </table>
            {% if schemas.count == 0 %}
            	<h4>No schemas yet....</h4>
            {% endif %}
        </div>
    </div>


{% endblock %}

data_generator/templates/data_generator/schema_view.html
{% extends "data_generator/base.html" %}
{% load static %}

{% block content %}

<div class="container">
        <div class="row mt-4">

            <h3>Datasets</h3>
            <div class="form-group col-md-3">
                <form method="POST" name="row-form" id="row_form">
                    {% csrf_token %}

                    {% for field in form.visible_fields %}
                        <label class="form-label">{{ field.label }}</label>
                        <input type="number" name="rows" id="row_form">

                       <!-- {{ field }} -->

                    {% endfor %}

                    <button type="submit" class="btn btn-success mt-2" onclick="return getData()">Generate</button>

                </form>
            </div>
            <div>
                <h3 style="text-align: center;">To see result ==> Refresh page</h3>
            </div>
            <table class="table mt-3">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Create</th>
                    <th scope="col">Status</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for file in schema.schema_files.all %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ file.created_at }}</td>
                        <td>
                           {% if file.status == 'Processing' %}
                                <div class='progress-wrapper'>
                                  <div id='progress-bar' class='progress-bar' style="background-color: #68a9ef; width: 0%;"></div>
                                </div>
                                <div id="progress-bar-message"></div>
                                <div id="celery-result"></div>
                            {% elif file.status == 'Ready' %}
                                <span class="badge bg-success">{{ file.status }}</span>
                            {% else %}
                                <span class="badge bg-danger">{{file.status }}</span>
                            {% endif %}
                        </td>
                        <td>
                            {% if file.status == 'Ready' %}
                                <a href="{{ file.file.url }}">Download</a>
                            {% endif %}
                            <span>
                                <a class="text-danger" href="{% url 'data_generator:delete_csv' schema.id file.id %}">Delete</a>
                            </span>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>

            </table>
            {% if schema.schema_files.count == 0 %}
            	<h4>No files yet....</h4>
            {% endif %}
        </div>
    </div>


    {% block custom_scripts %}
    {% if task_id %}
    <script>

        // vanilla JS version
        document.addEventListener("DOMContentLoaded", function () {
          var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
          CeleryProgressBar.initProgressBar(progressUrl);
        });

        function getData(e) {
            e.preventDefault();
        }

    </script>
    {% endif %}
    {% endblock custom_scripts %}


{% endblock %}